markdown: rdiscount
pygments: true
permalink: /blog/:year/:month/:title
paginate: 20
paginate_path: blog/page/:num
rdiscount:
  extensions: [smart]
title: Lynn's Log
production_url : honglin.info
description: "Do or do not. There is no try!"
disqus_shortname: lynnsinfo
analytics: UA-40333054-1
author:
  name: Lynn Chen
  github: homleen
  twitter: openapi
